### ISSUE TITLE
3D Buildings

### ISSUE THREAD

**Issue by KalipheGTU** [flux-labs/flux-site-extractor#11]
Import buildings with hight in 3D form

**Comment by javiz** [comment]
As per #10, I will be adding attributes for the building height if the data exists. Not sure if I will be creating a 3D building since many buildings do not contain this data, and I don't think having two types of output (mesh + polyline) is ideal.

**Comment by KalipheGTU** [comment]
Maybe for the buildings without data (attributions) you can add an option (set a rondom hight min and max)

**Comment by javiz** [comment]
I will consider adding this option, still need to figure it out on the UI side. Thanks for your input!

**Comment by lcbaz15** [comment]
Hi, 

Would it be possible to integrate the processes illustrated here with your application?
http://brian-horning.com/google-earth-to-obj-using-glintercept/

I'm interested in pursuing an application like this and would like to know your thoughts.

**Comment by javiz** [comment]
This feature has been added, let me know if it solves your needs.

**Comment by KalipheGTU** [comment]
and what about large area ?
Thank you 
great JOB
