### ISSUE TITLE
Include Flux units data in JSON package

### ISSUE THREAD

**Issue by AnthonyBuckleyThorp** [flux-labs/flux-site-extractor#5]
Include units according to new Flux standard (attached) with JSON sent in each data key. 

<img width="255" alt="units" src="https://cloud.githubusercontent.com/assets/13855791/15808589/be42a9ae-2b2f-11e6-8657-cd7ae2697166.PNG">

**Comment by javiz** [comment]
Fixed - both polylines and meshes now have units in the JSON output.
