### ISSUE TITLE
Openstreetmap

### ISSUE THREAD

**Issue by KalipheGTU** [flux-labs/flux-site-extractor#8]
if we can change the provider of the satellite images (means more providers) ex openstreetmap, yahoo, bing...etc.

**Comment by javiz** [comment]
The provider of the satellite images is Google Maps, but the data provider is Open Street Maps. Aside from OSM, I am not familiar with others that have an API for gathering map data. Like I mentioned in #9, I can't provide the satellite images for now, so I don't see the benefit of adding more providers for now.
