### ISSUE TITLE
Importe with texture

### ISSUE THREAD

**Issue by KalipheGTU** [flux-labs/flux-site-extractor#9]
importe area with textures (satellite, maps, topo..etc.)

**Comment by javiz** [comment]
Flux does not currently have a data type for images, so I'm afraid I can't provide this feature for now. What is your use case?

**Comment by KalipheGTU** [comment]
Ok!
and what abot a plugin inside sketchup directly? with satellites images!

**Comment by javiz** [comment]
If and when Flux handles images, I will add this feature. For now I'm marking it as closed.
